### PR TITLE
better differentiation between C and C++ linting & corresponding settings

### PR DESCRIPTION
**Pull request by GhostLyrics**

### CODE REVIEW

**Comment by dralley** [comment]
@GhostLyrics , would you mind bringing your Pull Request up to date with master and fixing the merge conflict?  My apologies for the delay.

**Comment by nirm03** [comment]
Actually, I already hand merged the relevant part of this PR. It was agreed by the author that this should suffice.

**Comment by dralley** [comment]
Awesome, didn't know about that.  Can this PR be closed then?

**Comment by GhostLyrics** [comment]
Not sure if you want to leave `fcxx-exceptions` enabled for C too, but the rest is already in master.

**Comment by dralley** [comment]
@GhostLyrics Good point.  I'll address it in PR #17

**Pull request closed without merging**
