### PR TITLE
don’t invoke the clang frontend directly, use the driver instead

### LINKED ISSUE #2: linter can't find standard header files, clang can.
This is disheartening to me, when called through the linter clang can not find standard header files like stdio.h

I'm working in C (not c++) and the linter is marking all my standard headers like errno and stdio ect as missing. however when I run clang via the command line myself like so `$ clang myfile.c` it finds everything just fine. 

my research indicates that it might have something to do with the `-cc1` option
http://clang.llvm.org/docs/FAQ.html#i-run-clang-cc1-and-get-weird-errors-about-missing-headers

### PR DESCRIPTION
**Pull request by Optiligence**
http://clang.llvm.org/docs/FAQ.html#i-run-clang-cc1-and-get-weird-errors-about-missing-headers
fixes #2

### CODE REVIEW

**Comment by dralley** [comment]
Tried it on my computer (Linux Mint 17), fix worked perfectly

**Comment by Optiligence** [comment]
I only tested it on Linux and Windows, but i’m pretty confident it’d also work on Mac.

**Comment by creationix** [comment]
Hmm, on my linux I applied the patch manually and get:

```
SublimeLinter: clang output:
clang: error: -E or -x required when input is from standard input 
SublimeLinter: clang: loop.c ['clang', '-fsyntax-only', '-fno-caret-diagnostics', '-fcxx-exceptions', '-Wall', '-I', '/home/tim/luvi/deps/luv/deps/libuv/include', '-I', '/home/tim/luvi/deps/luv/deps/luajit/src', '-I', '/home/tim/lit-glfw/glfw/include', '-'] 
SublimeLinter: clang output:
clang: error: -E or -x required when input is from standard input 
```

**Comment by creationix** [comment]
I got it working for me.  I'm writing C and not C++, so I had to add:

``` python
        if persist.get_syntax(self.view) == 'c':
            result += ' -x c '
```

after the similar section with C++

**Comment by dralley** [comment]
I combined it with PR #10 and it seems to fix the issue.

**Comment by Optiligence** [comment]
This PR is supposed to solve one problem for the moment. 
But PR #10 goes into the right direction, imo.

**Comment by creationix** [comment]
@Optiligence small scope is fine, but as-is, this PR makes things worse for my use case.  It goes from needing the hack mentioned in #2 to completely not working at all for C code.  My 2-line addition fixes it for C code.

**Comment by Optiligence** [comment]
@creationix There are other issues, i know, that’s why there’re other PRs. As it is, it can even be directly merged with PR #10, which wouldn’t be possible if i’d add more tiny fixes.

**Comment by nirm03** [comment]
@Optiligence Thanks for the PR, and sorry for the late response.
The reason I added the -cc1 in the first place was that it didn't seem to work in conjunction with standard input. Have you tested this both for C and C++?

**Comment by Optiligence** [comment]
@nirm03 as mentioned by @creationix it needs the `-x` to specify the language, which is currently only present for c++. #10 adds this option also for c. I can also add it here if you don’t plan on merging #10.

**Comment by nirm03** [comment]
@Optiligence that's ok I'll take care of it.
#10 seems to be addressing a specific need while this PR addresses a crucial issue,
so I'll merge in your PR along with the extra fix from creationix, and address #10 seperately.
Thanks

**Comment by dralley** [comment]
Are there any plans to merge this pull request soon?

**Comment by creationix** [comment]
Thanks for merging, but it appears the extra fix to make it work for C is missing.  Would you like a new PR for that tiny change?

**Comment by Optiligence** [comment]
did you look at the current source code?
https://github.com/nirm03/SublimeLinter-clang/blob/d3f53312f12f28b59d99ec544e98890e07345ef6/linter.py#L72

**Comment by creationix** [comment]
Nevermind, thanks for the fix!

**Pull request merged**
